name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: time docker build . --file Dockerfile --tag test:dev
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: Measure-Command { docker build . --file Dockerfile --tag test:dev | Out-Default }
  build-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: time docker build . --file Dockerfile --tag test:dev
  buildkit-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 time docker build . --file Dockerfile --tag test:dev
  buildkit-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 time docker build . --file Dockerfile --tag test:dev
  buildkit-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 Measure-Command { docker build . --file Dockerfile --tag test:dev | Out-Default }
